blueprint:
  name: Thermo room calibration - multiple thermos
  description: Adjust thermo temperature based on external room temp
  domain: automation
  input:
    room_temp_sensor:
      name: Room thermometer
      description: External room temp sensor
      selector:
        entity:
          domain: sensor
          device_class: temperature
    thermostats:
      name: List of thermostats
      description: Thermostats that needs calibration
      selector:
        entity:
          multiple: true
          domain: climate
    wanted_temp_input:
      name: Wanted temperature
      description: Wanted room temperature
      selector:
        entity:
          domain: input_number
    heating_main_switch:
      name: Main switch for heating
      description: input boolean to turn heating on or off
      selector: 
        entity:
          domain:
          - input_boolean
          multiple: false

  source_url: https://github.com/martin-olsen/home-assistant-scripts/blob/main/blueprints/automation/eve_thermo_room_calibration.yaml

mode: single

trigger:
  - platform: time_pattern
    minutes: "/10"  # every 10 minutes

condition:
- condition: state
  entity_id: !input heating_main_switch
  state: "on"

action:
  - variables:
      room_temp_id: !input room_temp_sensor
      room_temp: "{{ states(room_temp_id) | float }}"
      wanted_temp_id: !input wanted_temp_input
      wanted_temp: "{{ states(wanted_temp_id) | float }}"
  - repeat:
      for_each: !input thermostats
      sequence: 
        - service: climate.set_temperature
          target:
            entity_id: "{{ repeat.item }}"
          data:
            temperature: >-
              {{ (((wanted_temp + (state_attr( repeat.item, 'current_temperature') | float) - room_temp) * 2) | round(0)) / 2 }}
